# -*- coding: utf-8 -*-
"""Lista atividades_if_else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SJ9d_5HBWZ6F3UjH4Q7RYXFU-OMg1j-s
"""

#1  Leia dois números, faça a soma e apresente caso seja maior que 15

numero1 = float(input("digite o primeiro numero "))
numero2 = float(input("digite o segundo numero"))

soma = numero1 + numero2
print("O valor da soma e':", soma)

#2 Faça um programa que recebendo um valor inteiro, informe se o número é positivo, negativo ou neutro.

valor = int(input(" digite o numero "))
if valor > 0:
  print("O numero e' positivo")
elif valor  == 0:
  print("O numero e' neutro")
else:
  print("O numero e' negativo")

#3 Leia a idade e informe se a pessoa é maior ou menor de idade

idade = float(input("Digite a idade:"))
if idade >= 18:
  print("maior de idade")
else:
  print("menor de idade")

#4 Faça um programa que pergunte a temperatura atual para o usuário e mostre uma mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.

temperatura = float(input("Digite a temperatura atual:"))
if temperatura < 21:
  print("O dia esta frio")
elif temperatura >=21 and temperatura <= 23:
  print("O dia esta agradavel")
else:
  print("o dia esta calor")

#5 Faça um programa em linguagem Python que leia dois números inteiros e informe se estes são iguais ou diferentes

numerointeiro1 = int(input("Digite o primeiro numero inteiro"))
numerointeiro2 = int(input("Digite o segundo numero inteiro"))

if numerointeiro1 == numerointeiro2:
   print("numeros sao iguais")
else:
   print("numeros sao diferentes")

#6 Escreva um programa que verifique a validade de uma senha fornecida pelo usuário. A senha válida é o número 1234. Devem ser impressas as seguintes mensagens:
#* ACESSO PERMITIDO caso a senha seja válida.
#* ACESSO NEGADO caso a senha seja inválida.

senha = int(input("Digite a sua senha"))
if senha == 1234:
  print("ACESSO PERMITIDO")
else:
  print("ACESSO NEGADO")

#7 Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou igual a 7, informar que o aluno foi aprovado;
# se a média for maior ou igual a 5 mas menor do que 7, informar que o aluno está de exame; se a média for menor do que 5 informar que o aluno foi reprovado.

nota1 = float(input("Digite a primeira nota"))
nota2 = float(input("Digite a segunda nota"))
media = (nota1 + nota2)/2

if media >= 7:
  print(f'A media e {media:.2f}, aluno APROVADO')
elif media < 7 and media >= 5:
  print(f'A media e {media:.2f}, aluno de EXAME')
else:
  print(f'A media e {media:.2f}, aluno REPROVADO')

#8 Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os gols de cada time) e informe se o resultado foi um empate,
# se a vitória foi do primeiro time ou do segundo time.

print("Digite o placar do jogo")
time1 = int(input("Digite os gols do time1:"))
time2 = int(input("Digite os gols do time2:"))

if time1 == time2:
  print("O jogo foi empate")
elif time1 > time2:
  print("O time1 ganhou")
else:
  print("O time2 ganhou")

#9 Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno.
#Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.

turnos = ["M","V","N"] # variavel entre aspas indica string
turno = input("Em qual turno voce estuda? M-matutino ou V-Vespertino ou N-Noturno ")
if turno in turnos:
  if turno == "M": # variavel entre aspas indica string
    print("Bom dia!")
  elif turno == "V":
    print("Boa tarde!")
  else:
    print("Boa noite!")
else:
  print("Valor Invalido - escolha  M-matutino ou V-Vespertino ou N-Noturno")

#10 10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a classificação etária de acordo com as faixas de valores:
# Criança para 0 até 11 anos;
# Adolescente para 12 até 18 anos;
# Jovem para 19 até 24 anos;
# Adulto para 25 até 40 anos;
# Meia Idade para 41 até 60 anos;
# Idoso acima de 60 anos.

idade = int(input("Digite a sua idade:"))
if idade >= 0 and idade <= 11:
  print('Crianca')
elif idade > 11 and idade < 19:
  print('Adolescente')
elif idade > 18 and idade < 25:
  print('Jovem')
elif idade > 24 and idade < 41:
  print('Adulto')
elif idade > 40 and idade < 61:
  print('Meia Idade')
elif idade > 60:
  print('Idoso')

# 11. As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os
# reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
# salários até R$ 280,00 (incluindo) : aumento de 20%
# salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
# salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
# salários de R$ 1500,00 em diante : aumento de 5%

# Após o aumento ser realizado, informe na tela:
# o salário antes do reajuste;
# o percentual de aumento aplicado;
# o valor do aumento;
# o novo salário, após o aumento.

salario = float(input("Digite seu salario para calcular o reajuste: "))

if salario < 280:
  print(f"seu salario R${salario:.2f}")
  print("o percentual do aumento e de 20%")
  aumento =  (salario / 100 * 20)
  print(f"O valor do aumento e de {aumento}")
  print(f"O salario com reajuste R${salario + aumento:.2f}")

elif salario > 279.99 and salario < 700.01:
  print(f"seu salario e R${salario:.2f}")
  print("o percentual do aumento e de 15%")
  aumento =  (salario / 100 * 15)
  print(f"O valor do aumento e de {aumento}")
  print(f"O salario com reajuste R${salario + aumento:.2f}")

elif salario > 699.99 and salario < 1500.01:
  print(f"seu salario e R${salario:.2f}")
  print("o percentual do aumento e de 10%")
  aumento =  (salario / 100 * 10)
  print(f"O valor do aumento e de {aumento}")
  print(f"O salario com reajuste R${salario + aumento:.2f}")

elif salario > 1500:
  print(f"seu salario e R${salario:.2f}")
  print("o percentual do aumento e de 5%")
  aumento =  (salario / 100 * 5)
  print(f"O valor do aumento e de {aumento}")
  print(f"O salario com reajuste R${salario + aumento:.2f}")

# 12. Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.

dia = int(input("Digite o numero do dia da semana: "))

if dia == 1:
  print("Domingo")
elif dia == 2:
  print("Segunda")
elif dia == 3:
  print("Terca")
elif dia == 4:
  print("Quarta")
elif dia == 5:
  print("Quinta")
elif dia == 6:
  print("Sexta")
elif dia == 7:
  print("Sabado")
else:
  print("Valor invalido")

# 13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta
# do usuário, faça a devida conversão.


conversao = int(input("Digite 1 para converter Celsius p/ Fahrenheit ou 2 para converter Fahrenheit p/ Celsius"))

if conversao == 1:
  celsius = float(input('Digite a temperatura em Celsius: '))
  f = celsius * 1.8 + 32
  print(f'A conversao para Fahrenheit: {f:.2f}')

elif conversao == 2:
  Fahrenheit = float(input('Digite a temperatura em Fahrenheit: '))
  c = (Fahrenheit - 32) / 1.8
  print(f'A conversao para celsius: {c:.2f}')

else:
  print('Valor invalido')

# 14. Faça um programa que receba a idade de uma pessoa e imprima sua condição (obrigatória, optativa ou proibida), em relação ao ato de votar, conforme apresentado abaixo:
# Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
# Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar (optativo);
# Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar(obrigatório);
# Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).


idade = int(input("Digite sua idade"))

if idade < 16:
  print("Proibido votar")
elif idade > 15 and idade < 18:
  print("Voto opcional")
elif idade > 17 and idade < 65:
  print("Obrigatorio votar")
else:
  print("Voto opcional")

#15 . Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:
# “Telefonou para a vítima? “
# “Esteve no local do crime?”
# “Mora perto da vítima? “
# “Devia para a vítima? “
# “Já trabalhou com a vítima? “

print("Responda as seguintes perguntas como sim ou nao#")
pergunta1 = input("Telefonou para a vitima?").lower()
pergunta2 = input("Esteve no local do crime?").lower()
pergunta3 = input("Mora perto da vitima?").lower()
pergunta4 = input("Devia para a vitima?").lower()
pergunta5 = input("Ja trabalhou com a vitima?").lower()

positivas = 0

if pergunta1 == "sim":
  positivas += 1
if pergunta2 == "sim":
  positivas +=1
if pergunta3 == "sim":
  positivas += 1
if pergunta4 == "sim":
  positivas +=1
if pergunta5 == "sim":
  positivas +=1

if positivas == 2:
  print("Suspeita")
elif 3 <= positivas <= 4: #elif positivas >=3 and positivas <+4:
  print("Cumplice")
elif positivas == 5:
  print("bandidinho")
else:
  print("Inocente")

# 17. Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato.

produto1 = float(input('Digite o valor do primeiro produto'))
produto2 = float(input('Digite o valor do segundo produto'))
produto3 = float(input('Digite o valor do terceiro produto'))

if produto1 < produto2 and produto1 < produto3:
  print('Comprar produto 1')

elif produto2 < produto1 and produto2 < produto3:
  print('Comprar produto 2')

elif produto3 < produto1 and produto3 < produto2:
  print('Comprar produto 3')